### ISSUE TITLE
Should `superjson` be a dev or prod dependency?

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/babel-plugin-superjson-next#107]
Should `superjson` be a dev or prod dependency?

_Originally posted by @nemanjam in https://github.com/blitz-js/babel-plugin-superjson-next/issues/19#issuecomment-1019099240_

**Comment by Skn0tt** [comment]
I'd put them into prod dependency, since SuperJSON will need to be present in your application bundle in order for things to work. But considering that you're most likely using a bundler anyways, it won't make that much of a difference: https://jsramblings.com/do-dependencies-devdependencies-matter-when-using-webpack/

**Comment by nemanjam** [comment]
Thanks.

**Comment by nemanjam** [comment]
Thanks.
