### ISSUE TITLE
Get layout is not working anymore after adding plugin

### ISSUE THREAD

**Issue by Haberkamp** [blitz-js/babel-plugin-superjson-next#129]
I've added the plugin to my next.js app and fetching dates worked fine but the layouts we're missing completely.

next.js version: 12.2.4
superjson version: 1.9.1
babel-plugin-superjson-next version: 0.4.3

**Comment by Skn0tt** [comment]
Hi @Haberkamp! Could you share a reproduction repository? That'd make it a lot easier for me to reproduce this.

**Comment by Haberkamp** [comment]
Yes! [Here you go](https://github.com/Haberkamp/superjson-next-layout). After starting the server visit the `/layout` route. When you comment out the `getServerSideProps` variable of that page you'll be able to see the layout again.

**Comment by Skn0tt** [comment]
thx for the repro! I was able to reproduce and fix the error, it had to do with the order of the code emitted by this babel plugin.

@all-contributors please add @Haberkamp for bug

**Comment by Skn0tt** [comment]
published in https://github.com/blitz-js/babel-plugin-superjson-next/releases/tag/v0.4.4 :)

**Comment by Haberkamp** [comment]
Yea thank you!
