### ISSUE TITLE
Issue when using an export list for `getServerSideProps`

### ISSUE THREAD

**Issue by florian-milky** [blitz-js/babel-plugin-superjson-next#134]
Hi! I wanna report a small bug kind of similar to https://github.com/blitz-js/babel-plugin-superjson-next/issues/100

This did not work 🔴 
```
import {
  getServerSideProps,
  PreviewPage,
} from '../../../common-components/contentful-elements/pages/preview';

export { getServerSideProps };

export default PreviewPage;
```

I changed to 
```
import {
  getServerSideProps as getPreviewServerSideProps,
  PreviewPage,
} from '../../../common-components/contentful-elements/pages/preview';

export const getServerSideProps = getPreviewServerSideProps;

export default PreviewPage;
```
and it worked ✅

**Comment by Skn0tt** [comment]
Oh interesting! Yeah the babel transpilation logic is finicky 😅 The way I'd go about fixing this is to add a new testcase in https://github.com/blitz-js/babel-plugin-superjson-next/tree/main/test/pages, and then step through https://github.com/blitz-js/babel-plugin-superjson-next/blob/main/src/index.ts with a debugger to fix it.
Would you be interested in contributing a fix for this? I can also do it, just let me know.

**Comment by florian-milky** [comment]
@Skn0tt I'd be interested but I don't think I'll have the time. Sorry!

**Comment by Skn0tt** [comment]
opened a draft PR. not sure when I'll have some spare time to find a solution, but i'll get to it! in the meantime, i'm happy you found a workaround already.
