### ISSUE TITLE
Support Next `/app` Server Components

### ISSUE THREAD

**Issue by jokull** [blitz-js/babel-plugin-superjson-next#139]
It would be cool if this plugin also patched the network boundary between server and client components in Next 13 `/app`. If it's already supported it should be added to the README. Happy to help out if you think this is a good idea!

**Comment by Skn0tt** [comment]
Hey @jokull, thanks for opening the issue! Could you elaborate on why you closed it again? 😅

**Comment by jokull** [comment]
I thought `next-superjson-plugin` superseded this package. But I might be wrong :) 

Ran into an issue with it and opened a relevant issue for that.

**Comment by Skn0tt** [comment]
Nope, we'll keep on maintaining both until SWC plugins become stable :)

I'm not sure if it's possible to patch the network boundary between react client/server components. If you were to do this manually within your application's code, how would you approach that? Maybe we can try to replicate that in the Babel / SWC plugins.

**Comment by jokull** [comment]
"patch network boundary" is a terrible way to communicate what I was thinking. I just meant if this had a nice wrapper for Server Component > Client Component in `/app`.

**Comment by orionmiz** [comment]
@Skn0tt SWC Plugin has started supporting this feature. Sorry for the late feedback.

Here's a past issue used as RFC:
- https://github.com/blitz-js/next-superjson-plugin/issues/55

The point is that there's no way for the transpiler plugin to know which child component in a server component is the real client component.
So I approached it using a method that allows users to insert `data-superjson` attribute into the child client component manually.

Example: [Input](https://github.com/blitz-js/next-superjson-plugin/blob/canary/tests/fixture/app/general/code.js) / [Output](https://github.com/blitz-js/next-superjson-plugin/blob/canary/tests/fixture/app/general/output.js)

Do you have any better ideas?

**Comment by jokull** [comment]
I love this approach, using it already. I'll let @Skn0tt close it or keep open if he wants to do it with babel.

**Comment by Skn0tt** [comment]
This sounds like non-trivial added complexity. I have the assumption (not sure if its' right) that users who're using React Server Components will also be using SWC, so adding this functionality to the babel plugin wouldn't add any massive value. I'll close this issue for now.

To anyone who reads this: If you *need* this feature, please put a comment below! That helps me gauge the need for this. If we find substantial need for this from users of this plugin, i'll reconsider :)
