### ISSUE TITLE
Crash when hitting fallback on getStaticPaths

### ISSUE THREAD

**Issue by alexrohleder** [blitz-js/babel-plugin-superjson-next#15]
hey,

when using `getStaticPaths` with `fallback: true` I get this error every time I reach an route that was not returned by this function, in other words whenever the fallback is activated:

`Error: Not a valid SuperJSON payload.`

here is a reproduction repo:

0. https://github.com/alexrohleder/superjson-next-error-repro
1. go to any route other than index

**Comment by Skn0tt** [comment]
Thanks for letting us know! I‘ll look into it.

**Comment by Skn0tt** [comment]
@allcontributors add alexrohleder for bugs
