### ISSUE TITLE
Latest version (0.1.3) throws SyntaxError

### ISSUE THREAD

**Issue by arafatamim** [blitz-js/babel-plugin-superjson-next#2]
Version 0.1.3 throws `SyntaxError: Cannot use import statement outside a module` on a fresh Next.js install.
0.1.2 works though.

**Comment by flybayer** [comment]
@arafatamim thanks for reporting this!

**Comment by Skn0tt** [comment]
Thanks for reporting! We had some build process issues, they have been fixed with v0.1.4.
