### ISSUE TITLE
Does not work with decorated getServerSideProps

### ISSUE THREAD

**Issue by vincaslt** [blitz-js/babel-plugin-superjson-next#96]
I'm implementing auth with https://github.com/gladly-team/next-firebase-auth and it requires to decorate both getServerSideProps and the component with their HOFs.

```

export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
})(async ({ AuthUser }) => {
  ...
  return {
    props,
  };
});

export default withAuthUser<ServerSideProps>()(Component);
```

My payload includes Date and I logged it in the component - it's string.

**Comment by Skn0tt** [comment]
Hi @vincaslt! Thank you for opening this issue. I published a fix in v0.4.1, let me know if that didn't work.
